In [39]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
%matplotlib inline

In [40]:
sns.set_style("whitegrid")

In [41]:
data1 = pd.read_csv("BL-Flickr-Images-Book.csv")
data1.head()

,Identifier,Edition Statement,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Corporate Author,Corporate Contributors,Former owner,Engraver,Issuance type,Flickr URL,Shelfmarks
0,206,NaN,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12641.b.30.
1,216,NaN,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12626.cc.2.
2,218,NaN,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 12625.dd.1.
3,472,NaN,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 10369.bbb.15.
4,480,"A new edition, revised, etc.",London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",NaN,NaN,NaN,NaN,monographic,http://www.flickr.com/photos/britishlibrary/ta...,British Library HMNTS 9007.d.28.

In [42]:
data1.columns

Index(['Identifier', 'Edition Statement', 'Place of Publication',
       'Date of Publication', 'Publisher', 'Title', 'Author', 'Contributors',
       'Corporate Author', 'Corporate Contributors', 'Former owner',
       'Engraver', 'Issuance type', 'Flickr URL', 'Shelfmarks'],
      dtype='object')

In [43]:
to_drop = ['Edition Statement','Corporate Author', 'Corporate Contributors', 'Former owner',
       'Engraver','Issuance type','Shelfmarks']
data1.drop(columns = to_drop, inplace = True)

In [44]:
data1

,Identifier,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
0,206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
1,216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
2,218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
3,472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
4,480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...
...,...,...,...,...,...,...,...,...
8282,4158088,London,1838,NaN,"The Parochial History of Cornwall, founded on,...","GIDDY, afterwards GILBERT, Davies.","BOASE, Henry Samuel.|HALS, William.|LYSONS, Da...",http://www.flickr.com/photos/britishlibrary/ta...
8283,4158128,Derby,"1831, 32",M. Mozley & Son,The History and Gazetteer of the County of Der...,"GLOVER, Stephen - of Derby","NOBLE, Thomas.",http://www.flickr.com/photos/britishlibrary/ta...
8284,4159563,London,[1806]-22,T. Cadell and W. Davies,Magna Britannia; being a concise topographical...,"LYSONS, Daniel - M.A., F.R.S., and LYSONS (Sam...","GREGSON, Matthew.|LYSONS, Samuel - F.R.S",http://www.flickr.com/photos/britishlibrary/ta...
8285,4159587,Newcastle upon Tyne,1834,Mackenzie & Dent,"An historical, topographical and descriptive v...","Mackenzie, E. (Eneas)","ROSS, M. - of Durham",http://www.flickr.com/photos/britishlibrary/ta...
8286,4160339,London,1834-43,NaN,Collectanea Topographica et Genealogica. [Firs...,NaN,"BANDINEL, Bulkeley.|Nichols, John Gough",http://www.flickr.com/photos/britishlibrary/ta...

In [45]:
#is_unique helps us identify wether the whole column has unique values or not
data1["Place of Publication"].is_unique

False

In [46]:
data1["Identifier"].is_unique

True

In [47]:
#we normal should have a unique index which can making slicing a bit more easier 
data1 = data1.set_index("Identifier")
data1.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879 [1878],S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...

"""Unlike primary keys in SQL, a Pandas Index doesn’t make any guarantee of being unique, 
although many indexing and merging operations will notice a speedup in runtime if it is."""

In [48]:
#regrex formatting was used to extract the dates from an unformatted date columns
extr = data1["Date of Publication"].str.extract(r'^(\d{4})', expand = False)
extr.head()

Identifier
206    1879
216    1868
218    1869
472    1851
480    1857
Name: Date of Publication, dtype: object

In [49]:
#converts the dates into numeric to perform computaions on them 
data1["Date of Publication"] = pd.to_numeric(extr)
data1["Date of Publication"].dtype

dtype('float64')

In [50]:
#finding the percentage of missing data 
date_precentage_missing = str(round((data1["Date of Publication"].isnull().sum() / len(data1["Date of Publication"])) * 100,2)) + " %"
print(date_precentage_missing)

11.72 %

In [51]:
data1.head()

,Place of Publication,Date of Publication,Publisher,Title,Author,Contributors,Flickr URL
Identifier,,,,,,,
206,London,1879.0,S. Tinsley & Co.,Walter Forbes. [A novel.] By A. A,A. A.,"FORBES, Walter.",http://www.flickr.com/photos/britishlibrary/ta...
216,London; Virtue & Yorston,1868.0,Virtue & Co.,All for Greed. [A novel. The dedication signed...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
218,London,1869.0,"Bradbury, Evans & Co.",Love the Avenger. By the author of “All for Gr...,"A., A. A.","BLAZE DE BURY, Marie Pauline Rose - Baroness",http://www.flickr.com/photos/britishlibrary/ta...
472,London,1851.0,James Darling,"Welsh Sketches, chiefly ecclesiastical, to the...","A., E. S.","Appleyard, Ernest Silvanus.",http://www.flickr.com/photos/britishlibrary/ta...
480,London,1857.0,Wertheim & Macintosh,"[The World in which I live, and my place in it...","A., E. S.","BROOME, John Henry.",http://www.flickr.com/photos/britishlibrary/ta...

In [52]:
data1["Place of Publication"].value_counts()

London                     3868
Paris                       479
Edinburgh                   208
New York                    177
Leipzig                     119
                           ...
London, Derby [printed]       1
Portland [Maine]              1
Санктпетербургъ, 1863         1
Shaftesbury                   1
Providence, R.I               1
Name: Place of Publication, Length: 1441, dtype: int64

In [53]:
pub1 = data1["Place of Publication"].str.contains('London')
pub2 = data1["Place of Publication"].str.contains('Oxford')

In [54]:
#np.where is used to apply a condition on a series. pub1 == True if the string contains London if yes replace it with "London" else do the "Oxford" np.where statement 
data1["Place of Publication"] = np.where(pub1, "London", np.where(pub2, "Oxford",data1["Place of Publication"].str.replace("-", " ")))

In [55]:
university_towns = []
with open ("university_towns.txt") as file:
    for line in file:
        if "[edit]" in line:
            state = line
        else:
            university_towns.append((state, line))
            
university_towns

[('Alabama[edit]\n', 'Auburn (Auburn University)[1]\n'),
 ('Alabama[edit]\n', 'Florence (University of North Alabama)\n'),
 ('Alabama[edit]\n', 'Jacksonville (Jacksonville State University)[2]\n'),
 ('Alabama[edit]\n', 'Livingston (University of West Alabama)[2]\n'),
 ('Alabama[edit]\n', 'Montevallo (University of Montevallo)[2]\n'),
 ('Alabama[edit]\n', 'Troy (Troy University)[2]\n'),
 ('Alabama[edit]\n',
  'Tuscaloosa (University of Alabama, Stillman College, Shelton State)[3][4]\n'),
 ('Alabama[edit]\n', 'Tuskegee (Tuskegee University)[5]\n'),
 ('Alaska[edit]\n', 'Fairbanks (University of Alaska Fairbanks)[2]\n'),
 ('Arizona[edit]\n', 'Flagstaff (Northern Arizona University)[6]\n'),
 ('Arizona[edit]\n', 'Tempe (Arizona State University)\n'),
 ('Arizona[edit]\n', 'Tucson (University of Arizona)\n'),
 ('Arkansas[edit]\n',
  'Arkadelphia (Henderson State University, Ouachita Baptist University)[2]\n'),
 ('Arkansas[edit]\n',
  'Conway (Central Baptist College, Hendrix College, University of Central Arkansas)[2]\n'),
 ('Arkansas[edit]\n', 'Fayetteville (University of Arkansas)[7]\n'),
 ('Arkansas[edit]\n', 'Jonesboro (Arkansas State University)[8]\n'),
 ('Arkansas[edit]\n', 'Magnolia (Southern Arkansas University)[2]\n'),
 ('Arkansas[edit]\n',
  'Monticello (University of Arkansas at Monticello)[2]\n'),
 ('Arkansas[edit]\n', 'Russellville (Arkansas Tech University)[2]\n'),
 ('Arkansas[edit]\n', 'Searcy (Harding University)[5]\n'),
 ('California[edit]\n', 'Angwin (Pacific Union College)[2]\n'),
 ('California[edit]\n', 'Arcata (Humboldt State University)[5]\n'),
 ('California[edit]\n', 'Berkeley (University of California, Berkeley)[5]\n'),
 ('California[edit]\n', 'Chico (California State University, Chico)[2]\n'),
 ('California[edit]\n',
  'Claremont (Claremont McKenna College, Pomona College, Harvey Mudd College, Scripps College, Pitzer College, Keck Graduate Institute, Claremont Graduate University)[5]\n'),
 ('California[edit]\n', 'Cotati (California State University, Sonoma)[2]\n'),
 ('California[edit]\n', 'Davis (University of California, Davis)[1]\n'),
 ('California[edit]\n', 'Irvine (University of California, Irvine)\n'),
 ('California[edit]\n',
  'Isla Vista (University of California, Santa Barbara)[2]\n'),
 ('California[edit]\n',
  'University Park, Los Angeles (University of Southern California)\n'),
 ('California[edit]\n', 'Merced (University of California, Merced)\n'),
 ('California[edit]\n', 'Orange (Chapman University)\n'),
 ('California[edit]\n', 'Palo Alto (Stanford University)\n'),
 ('California[edit]\n',
  'Pomona (Cal Poly Pomona, WesternU)[9][10][11] and formerly Pomona College\n'),
 ('California[edit]\n', 'Redlands (University of Redlands)\n'),
 ('California[edit]\n',
  'Riverside (University of California, Riverside, California Baptist University, La Sierra University)\n'),
 ('California[edit]\n',
  'Sacramento (California State University, Sacramento)\n'),
 ('California[edit]\n',
  'University District, San Bernardino (California State University, San Bernardino, American Sports University)\n'),
 ('California[edit]\n',
  'San Diego (University of California, San Diego, San Diego State University)\n'),
 ('California[edit]\n',
  'San Luis Obispo (California Polytechnic State University)[2]\n'),
 ('California[edit]\n',
  'Santa Barbara (Fielding Graduate University, Santa Barbara City College, University of California, Santa Barbara, Westmont College)[2]\n'),
 ('California[edit]\n',
  'Santa Cruz (University of California, Santa Cruz)[2]\n'),
 ('California[edit]\n', 'Turlock (California State University, Stanislaus)\n'),
 ('California[edit]\n',
  'Westwood, Los Angeles (University of California, Los Angeles)[2]\n'),
 ('California[edit]\n', 'Whittier (Whittier CollegeRio Hondo College)\n'),
 ('Colorado[edit]\n', 'Alamosa (Adams State College)[2]\n'),
 ('Colorado[edit]\n', 'Boulder (University of Colorado at Boulder)[12]\n'),
 ('Colorado[edit]\n', 'Durango (Fort Lewis College)[2]\n'),
 ('Colorado[edit]\n', 'Fort Collins (Colorado State University)[13]\n'),
 ('Colorado[edit]\n', 'Golden (Colorado School of Mines)\n'),
 ('Colorado[edit]\n', 'Grand Junction (Colorado Mesa University)\n'),
 ('Colorado[edit]\n', 'Greeley (University of Northern Colorado)\n'),
 ('Colorado[edit]\n', 'Gunnison (Western State College)[2]\n'),
 ('Colorado[edit]\n', 'Pueblo, Colorado (Colorado State University-Pueblo)\n'),
 ('Connecticut[edit]\n',
  'Fairfield (Fairfield University, Sacred Heart University)\n'),
 ('Connecticut[edit]\n', 'Middletown (Wesleyan University)\n'),
 ('Connecticut[edit]\n',
  'New Britain (Central Connecticut State University)\n'),
 ('Connecticut[edit]\n',
  'New Haven (Yale University, University of New Haven, Southern Connecticut State University, Albertus Magnus College, Quinnipiac University)[14]\n'),
 ('Connecticut[edit]\n',
  'New London (Connecticut College, US Coast Guard Academy, Mitchell College)[2]\n'),
 ('Connecticut[edit]\n', 'Storrs (University of Connecticut)[2]\n'),
 ('Connecticut[edit]\n',
  'Willimantic (Eastern Connecticut State University)[2]\n'),
 ('Delaware[edit]\n', 'Dover (Delaware State University)[1]\n'),
 ('Delaware[edit]\n', 'Newark (University of Delaware)[1]\n'),
 ('Florida[edit]\n', 'Ave Maria (Ave Maria University)\n'),
 ('Florida[edit]\n', 'Boca Raton (Florida Atlantic University)\n'),
 ('Florida[edit]\n', 'Coral Gables (University of Miami)\n'),
 ('Florida[edit]\n', 'DeLand (Stetson University)[5]\n'),
 ('Florida[edit]\n', 'Estero (Florida Gulf Coast University)\n'),
 ('Florida[edit]\n',
  'Gainesville (University of Florida, Santa Fe College)\n'),
 ('Florida[edit]\n', 'Orlando (University of Central Florida)\n'),
 ('Florida[edit]\n',
  'Sarasota (New College of Florida, Ringling College of Art and Design, State College of Florida, Manatee-Sarasota, University of South Florida Sarasota-Manatee)\n'),
 ('Florida[edit]\n', 'St. Augustine (Flagler College)\n'),
 ('Florida[edit]\n', 'St. Leo (St. Leo University)\n'),
 ('Florida[edit]\n',
  'Tallahassee (Florida State University, Florida A&M University)\n'),
 ('Florida[edit]\n', 'Tampa (University of South Florida)\n'),
 ('Georgia[edit]\n', 'Albany (Albany State University)\n'),
 ('Georgia[edit]\n', 'Athens (University of Georgia)[15]\n'),
 ('Georgia[edit]\n',
  'Atlanta (Georgia State University, Georgia Tech, Emory)[2]\n'),
 ('Georgia[edit]\n',
  'Carrollton (University of West Georgia)[2]*Dahlonega (North Georgia College & State University)[2]\n'),
 ('Georgia[edit]\n', 'Demorest (Piedmont College)[2]\n'),
 ('Georgia[edit]\n', 'Fort Valley (Fort Valley State University)[2]\n'),
 ('Georgia[edit]\n', 'Kennesaw (Kennesaw State University)\n'),
 ('Georgia[edit]\n',
  'Milledgeville (Georgia College & State University)[2]\n'),
 ('Georgia[edit]\n', 'Mount Vernon (Brewton-Parker College)[2]\n'),
 ('Georgia[edit]\n', 'Oxford (Oxford College)\n'),
 ('Georgia[edit]\n', 'Rome (Berry College, Shorter University)\n'),
 ('Georgia[edit]\n',
  'Savannah (Armstrong Atlantic State University, Savannah State University, Savannah College of Art and Design)\n'),
 ('Georgia[edit]\n', 'Statesboro (Georgia Southern University)[5]\n'),
 ('Georgia[edit]\n', 'Valdosta (Valdosta State University)[2]\n'),
 ('Georgia[edit]\n', 'Waleska (Reinhardt College)[2]\n'),
 ('Georgia[edit]\n', 'Young Harris (Young Harris College)[2]\n'),
 ('Hawaii[edit]\n', 'Manoa (University of Hawaii at Manoa)[2]\n'),
 ('Idaho[edit]\n', 'Moscow (University of Idaho)[2]\n'),
 ('Idaho[edit]\n', 'Pocatello (Idaho State University)[2]\n'),
 ('Idaho[edit]\n', 'Rexburg (BYU-Idaho)[2]\n'),
 ('Illinois[edit]\n',
  'Carbondale (Southern Illinois University Carbondale)[5]\n'),
 ('Illinois[edit]\n',
  'Champaign–Urbana (University of Illinois at Urbana–Champaign)[5]\n'),
 ('Illinois[edit]\n', 'Charleston (Eastern Illinois University)[2]\n'),
 ('Illinois[edit]\n', 'DeKalb (Northern Illinois University)[2]\n'),
 ('Illinois[edit]\n',
  'Edwardsville (Southern Illinois University Edwardsville)[2]\n'),
 ('Illinois[edit]\n', 'Evanston (Northwestern University)[2]\n'),
 ('Illinois[edit]\n', 'Lebanon (McKendree University)[2]\n'),
 ('Illinois[edit]\n', 'Macomb (Western Illinois University)[2]\n'),
 ('Illinois[edit]\n', 'Normal (Illinois State University)[2]\n'),
 ('Illinois[edit]\n', 'Peoria (Bradley University)\n'),
 ('Indiana[edit]\n', 'Bloomington (Indiana University Bloomington)[5]\n'),
 ('Indiana[edit]\n', 'Crawfordsville (Wabash College)\n'),
 ('Indiana[edit]\n', 'Greencastle (DePauw University)[5]\n'),
 ('Indiana[edit]\n', 'Hanover (Hanover College)[2]\n'),
 ('Indiana[edit]\n', 'Marion (Indiana Wesleyan University)[2]\n'),
 ('Indiana[edit]\n', 'Muncie (Ball State University)[2]\n'),
 ('Indiana[edit]\n', 'Oakland City (Oakland City University)[2]\n'),
 ('Indiana[edit]\n', 'Richmond (Earlham College)[2]\n'),
 ('Indiana[edit]\n', 'South Bend (Notre Dame University[2])\n'),
 ('Indiana[edit]\n',
  'Terre Haute (Indiana State University, Rose-Hulman Institute of Technology)[2]\n'),
 ('Indiana[edit]\n', 'Upland (Taylor University)[2]\n'),
 ('Indiana[edit]\n', 'Valparaiso (Valparaiso University)\n'),
 ('Indiana[edit]\n', 'West Lafayette (Purdue University)[2]\n'),
 ('Iowa[edit]\n', 'Ames (Iowa State University)[2]\n'),
 ('Iowa[edit]\n', 'Cedar Falls (University of Northern Iowa)[2]\n'),
 ('Iowa[edit]\n', 'Cedar Rapids, Iowa (Coe College )\n'),
 ('Iowa[edit]\n', 'Decorah (Luther College)[5]\n'),
 ('Iowa[edit]\n', 'Fayette (Upper Iowa University)[2]\n'),
 ('Iowa[edit]\n', 'Grinnell (Grinnell College)[15]\n'),
 ('Iowa[edit]\n', 'Iowa City (University of Iowa)[15]\n'),
 ('Iowa[edit]\n', 'Lamoni (Graceland University)[2]\n'),
 ('Iowa[edit]\n', 'Mount Vernon, (Cornell College)\n'),
 ('Iowa[edit]\n', 'Orange City (Northwestern College)[2]\n'),
 ('Iowa[edit]\n', 'Sioux Center (Dordt College)[2]\n'),
 ('Iowa[edit]\n', 'Storm Lake (Buena Vista University)[2]\n'),
 ('Iowa[edit]\n', 'Waverly (Wartburg College)[2]\n'),
 ('Kansas[edit]\n', 'Baldwin City (Baker University)[5]\n'),
 ('Kansas[edit]\n', 'Emporia (Emporia State University)[2]\n'),
 ('Kansas[edit]\n', 'Hays (Fort Hays State University)[2]\n'),
 ('Kansas[edit]\n',
  'Lawrence (University of Kansas, Haskell Indian Nations University)[15]\n'),
 ('Kansas[edit]\n',
  'Manhattan (Kansas State University, Manhattan Christian College)[15]\n'),
 ('Kansas[edit]\n', 'Pittsburg (Pittsburg State University)[2]\n'),
 ('Kentucky[edit]\n', 'Bowling Green (Western Kentucky University)[2]\n'),
 ('Kentucky[edit]\n', 'Columbia (Lindsey Wilson College)[2]\n'),
 ('Kentucky[edit]\n', 'Georgetown (Georgetown College)\n'),
 ('Kentucky[edit]\n', 'Highland Heights (Northern Kentucky University)\n'),
 ('Kentucky[edit]\n',
  'Lexington (University of Kentucky, Transylvania University[5]\n'),
 ('Kentucky[edit]\n', 'Louisville (University of Louisville)\n'),
 ('Kentucky[edit]\n', 'Morehead (Morehead State University)[2]\n'),
 ('Kentucky[edit]\n', 'Murray (Murray State University)[5]\n'),
 ('Kentucky[edit]\n', 'Richmond (Eastern Kentucky University)[2]\n'),
 ('Kentucky[edit]\n', 'Williamsburg (University of the Cumberlands)[2]\n'),
 ('Kentucky[edit]\n',
  'Wilmore (Asbury University, Asbury Theological Seminary)[2]\n'),
 ('Louisiana[edit]\n',
  'Baton Rouge (Louisiana State University, Southern University)\n'),
 ('Louisiana[edit]\n', 'Grambling (Grambling State University)[5]\n'),
 ('Louisiana[edit]\n', 'Hammond (Southeastern Louisiana University)[2]\n'),
 ('Louisiana[edit]\n', 'Lafayette (University of Louisiana at Lafayette)\n'),
 ('Louisiana[edit]\n', 'Monroe (University of Louisiana at Monroe)[2]\n'),
 ('Louisiana[edit]\n', 'Natchitoches (Northwestern State University)[2]\n'),
 ('Louisiana[edit]\n', 'Ruston (Louisiana Tech University)[2]\n'),
 ('Louisiana[edit]\n', 'Thibodaux (Nicholls State University)[2]\n'),
 ('Maine[edit]\n', 'Augusta (University of Maine at Augusta)[2]\n'),
 ('Maine[edit]\n', 'Bar Harbor (College of the Atlantic)\n'),
 ('Maine[edit]\n', 'Brunswick (Bowdoin College)\n'),
 ('Maine[edit]\n', 'Farmington (University of Maine at Farmington)[2]\n'),
 ('Maine[edit]\n', 'Fort Kent (University of Maine at Fort Kent)\n'),
 ('Maine[edit]\n', 'Gorham (University of Southern Maine)[2]\n'),
 ('Maine[edit]\n', 'Lewiston, Maine (Bates College)\n'),
 ('Maine[edit]\n', 'Orono (University of Maine)[2]\n'),
 ('Maine[edit]\n', 'Waterville (Thomas College, Colby College)\n'),
 ('Maryland[edit]\n',
  "Annapolis (United States Naval Academy, St. John's College)\n"),
 ('Maryland[edit]\n', 'Chestertown (Washington College)[2]\n'),
 ('Maryland[edit]\n',
  'College Park (University of Maryland, College Park)[16]\n'),
 ('Maryland[edit]\n', 'Cumberland (Allegany College of Maryland)\n'),
 ('Maryland[edit]\n', "Emmitsburg (Mount St. Mary's University)[2]\n"),
 ('Maryland[edit]\n', 'Frostburg (Frostburg State University)[5]\n'),
 ('Maryland[edit]\n',
  'Princess Anne (University of Maryland Eastern Shore)[5]\n'),
 ('Maryland[edit]\n', 'Towson (Towson University, Goucher College)[2]\n'),
 ('Maryland[edit]\n', 'Salisbury (Salisbury University)[2]\n'),
 ('Maryland[edit]\n', 'Westminster (McDaniel College)\n'),
 ('Massachusetts[edit]\n',
  'Boston (Boston University, Boston College, Boston Conservatory, New England Conservatory, Brandeis University, Northeastern University, UMass Boston, Emmanuel College, Bunker Hill Community College, Roxbury Community College, Suffolk University, Simmons College, among many others)\n'),
 ('Massachusetts[edit]\n', 'Bridgewater (Bridgewater State College)[2]\n'),
 ('Massachusetts[edit]\n',
  'Cambridge (Harvard University, Massachusetts Institute of Technology)(Lesley University, Cambridge College, Longy School of Music)[15]\n'),
 ('Massachusetts[edit]\n', 'Chestnut Hill (Boston College)\n'),
 ('Massachusetts[edit]\n', 'The Colleges of Worcester Consortium:\n'),
 ('Massachusetts[edit]\n', 'Dudley (Nichols College)\n'),
 ('Massachusetts[edit]\n',
  'North Grafton (Cummings School of Veterinary Medicine at Tufts University)\n'),
 ('Massachusetts[edit]\n', 'Paxton (Anna Maria College)\n'),
 ('Massachusetts[edit]\n',
  'Worcester (Assumption, Becker, Clark University, Holy Cross, Mass. College of Pharmacy & Health Sciences, Quinsigamond Community College, UMass Medical School, Worcester State University, Worcester Polytechnic Institute)\n'),
 ('Massachusetts[edit]\n',
  'The Five College Region of Western Massachusetts:\n'),
 ('Massachusetts[edit]\n',
  'Amherst (Amherst College, Hampshire College, University of Massachusetts Amherst)[15]\n'),
 ('Massachusetts[edit]\n', 'Northampton (Smith College)\n'),
 ('Massachusetts[edit]\n', 'South Hadley (Mount Holyoke College)\n'),
 ('Massachusetts[edit]\n', 'Fitchburg (Fitchburg State College)\n'),
 ('Massachusetts[edit]\n',
  'North Adams (Massachusetts College of Liberal Arts)\n'),
 ('Massachusetts[edit]\n',
  'Springfield (American International College), (Springfield College), and (Western New England College)\n'),
 ('Massachusetts[edit]\n',
  'Waltham (Bentley University), (Brandeis University)\n'),
 ('Massachusetts[edit]\n', 'Williamstown (Williams College)\n'),
 ('Massachusetts[edit]\n', 'Framingham (Framingham State University)\n'),
 ('Michigan[edit]\n', 'Adrian (Adrian College, Siena Heights University)\n'),
 ('Michigan[edit]\n', 'Albion (Albion College)[17]\n'),
 ('Michigan[edit]\n', 'Allendale (Grand Valley State University)\n'),
 ('Michigan[edit]\n', 'Alma (Alma College)\n'),
 ('Michigan[edit]\n', 'Ann Arbor (University of Michigan)[1]\n'),
 ('Michigan[edit]\n', 'Berrien Springs (Andrews University)[2]\n'),
 ('Michigan[edit]\n', 'Big Rapids (Ferris State University)[2]\n'),
 ('Michigan[edit]\n', 'East Lansing (Michigan State University)[2]\n'),
 ('Michigan[edit]\n',
  'Flint (Kettering University, University of Michigan-Flint)\n'),
 ('Michigan[edit]\n', 'Hillsdale (Hillsdale College)\n'),
 ('Michigan[edit]\n', 'Houghton (Michigan Technological University)[5]\n'),
 ('Michigan[edit]\n',
  'Kalamazoo (Western Michigan University, Kalamazoo College)[2]\n'),
 ('Michigan[edit]\n', 'Marquette (Northern Michigan University)[2]\n'),
 ('Michigan[edit]\n', 'Midland (Northwood University)\n'),
 ('Michigan[edit]\n', 'Mount Pleasant (Central Michigan University)[2]\n'),
 ('Michigan[edit]\n', 'Olivet (Olivet College)[2]\n'),
 ('Michigan[edit]\n', 'Saginaw (Saginaw Valley State University)\n'),
 ('Michigan[edit]\n', 'Sault Ste. Marie (Lake Superior State University)\n'),
 ('Michigan[edit]\n', 'Spring Arbor (Spring Arbor University)[2]\n'),
 ('Michigan[edit]\n', 'Ypsilanti (Eastern Michigan University)[2]\n'),
 ('Minnesota[edit]\n', 'Bemidji (Bemidji State University)[2]\n'),
 ('Minnesota[edit]\n', 'Crookston (University of Minnesota Crookston)[2]\n'),
 ('Minnesota[edit]\n',
  'Duluth (University of Minnesota Duluth, Lake Superior College, The College of St. Scholastica, University of Wisconsin–Superior, Duluth Business University\n'),
 ('Minnesota[edit]\n', 'Faribault, South Central College\n'),
 ('Minnesota[edit]\n',
  'Mankato (Minnesota State University, Mankato),[2] Bethany Lutheran College\n'),
 ('Minnesota[edit]\n', 'Marshall (Southwest Minnesota State University)[2]\n'),
 ('Minnesota[edit]\n',
  'Moorhead (Minnesota State University, Moorhead, Concordia College)[18]\n'),
 ('Minnesota[edit]\n', 'Morris (University of Minnesota Morris)[2]\n'),
 ('Minnesota[edit]\n', 'Northfield (Carleton College, St. Olaf College)[5]\n'),
 ('Minnesota[edit]\n', 'North Mankato, South Central College\n'),
 ('Minnesota[edit]\n',
  'St. Cloud (St. Cloud State University, The College of St. Scholastica)[2]\n'),
 ('Minnesota[edit]\n', 'St. Joseph (College of Saint Benedict)[2]\n'),
 ('Minnesota[edit]\n', 'St. Peter (Gustavus Adolphus College)[2]\n'),
 ('Minnesota[edit]\n',
  "Winona (Winona State University, St. Mary's University of Minnesota)[19]\n"),
 ('Mississippi[edit]\n', 'Cleveland (Delta State University)[2]\n'),
 ('Mississippi[edit]\n',
  'Hattiesburg (University of Southern Mississippi)[20]\n'),
 ('Mississippi[edit]\n',
  'Itta Bena (Mississippi Valley State University)[2]\n'),
 ('Mississippi[edit]\n', 'Oxford (University of Mississippi)[2]\n'),
 ('Mississippi[edit]\n', 'Starkville (Mississippi State University)[2]\n'),
 ('Missouri[edit]\n', 'Bolivar (Southwest Baptist University)[2]\n'),
 ('Missouri[edit]\n',
  'Cape Girardeau (Southeast Missouri State University)[2]\n'),
 ('Missouri[edit]\n',
  'Columbia (University of Missouri, Stephens College, Columbia College)[20]\n'),
 ('Missouri[edit]\n', 'Fayette (Central Methodist University)[2]\n'),
 ('Missouri[edit]\n',
  'Fulton (Westminster College and William Woods University).\n'),
 ('Missouri[edit]\n',
  'Kirksville (Truman State University, A. T. Still University)[2]\n'),
 ('Missouri[edit]\n', 'Maryville (Northwest Missouri State University)[2]\n'),
 ('Missouri[edit]\n',
  'Rolla (Missouri University of Science and Technology)[2]\n'),
 ('Missouri[edit]\n', 'Warrensburg (University of Central Missouri)[5]\n'),
 ('Montana[edit]\n', 'Bozeman (Montana State University)[2]\n'),
 ('Montana[edit]\n', 'Dillon (University of Montana Western)[2]\n'),
 ('Montana[edit]\n', 'Missoula (University of Montana)[5]\n'),
 ('Nebraska[edit]\n', 'Chadron (Chadron State College)[5]\n'),
 ('Nebraska[edit]\n', 'Crete (Doane College)[2]\n'),
 ('Nebraska[edit]\n', 'Kearney (University of Nebraska at Kearney)[2]\n'),
 ('Nebraska[edit]\n', 'Lincoln (University of Nebraska at Lincoln)[5]\n'),
 ('Nebraska[edit]\n', 'Peru (Peru State College)[2]\n'),
 ('Nebraska[edit]\n', 'Seward (Concordia University)[2]\n'),
 ('Nebraska[edit]\n', 'Wayne (Wayne State College)[2]\n'),
 ('Nevada[edit]\n', 'Las Vegas (University of Nevada, Las Vegas)\n'),
 ('Nevada[edit]\n', 'Reno (University of Nevada, Reno)\n'),
 ('New Hampshire[edit]\n',
  'New London, New Hampshire (Colby-Sawyer College)\n'),
 ('New Hampshire[edit]\n', 'Durham (University of New Hampshire)[2]\n'),
 ('New Hampshire[edit]\n', 'Hanover (Dartmouth College)[5]\n'),
 ('New Hampshire[edit]\n', 'Henniker (New England College)\n'),

In [56]:
data2 = pd.DataFrame(university_towns, columns = ["State", "Region_Name"])
data2.head()

             State                                        Region_Name
0  Alabama[edit]\n                    Auburn (Auburn University)[1]\n
1  Alabama[edit]\n           Florence (University of North Alabama)\n
2  Alabama[edit]\n  Jacksonville (Jacksonville State University)[2]\n
3  Alabama[edit]\n       Livingston (University of West Alabama)[2]\n
4  Alabama[edit]\n         Montevallo (University of Montevallo)[2]\n

In [57]:
# def filtered(item):
#     if item.contain("("):
#         return item[:item.find("(")]
#     elif item.contain("["):
#         return item[:item.find("[")]
#     else:
#         return item

# data2.applymap(filtered)
# data2.head()